### ISSUE TITLE
Неплохо

### ISSUE THREAD

**Issue by stepinbefore** [Kylmakalle/tgvkbot#1]
Еще бы помимо текста отправлять бы вложения, вообще было бы супер)

**Comment by Kylmakalle** [comment]
Да, планирую, у вк немного странная и сложная система загрузки вложений, поэтому пока что их можно только [получать](https://github.com/Kylmakalle/tgvkbot/commit/56917be9af3e1895eec5021cfdb53bac8240a762)

**Comment by Kylmakalle** [comment]
Теперь и [Отправлять](https://github.com/Kylmakalle/tgvkbot/commit/7b41a06898cb51d700fe71eb938a773e72ee8fea)
