### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by amazing-c-er** [Kylmakalle/tgvkbot#34]
Есть инструкция, как запустить в windows?
Чтобы проверить работу бота после кастомизации
В инете не могу что-то найти..

**Comment by amazing-c-er** [comment]
Как ввести Телеграм токен и запустить проект через пк?

**Comment by Kylmakalle** [comment]
1. Установить Docker
2. Установить docker-compose
3. https://github.com/Kylmakalle/tgvkbot/blob/b896c8e00fbc67251d8952773e8c6622cb3fe6ba/install.sh#L37-L38
4. https://github.com/Kylmakalle/tgvkbot/blob/b896c8e00fbc67251d8952773e8c6622cb3fe6ba/install.sh#L56-L57

**Comment by amazing-c-er** [comment]
После установки
1. Запускаю setenv.py (ввожу Телеграм токен, создается env-file)
Дальше нужно ввести команду `docker-compose -f docker-compose.local.yml up` , так ведь?
Если так, то у меня ошибку выдает
Подскажите пожл, может я что-то пропустил?

**Comment by Kylmakalle** [comment]
Нужен лог ошибки @amazing-c-er
