### ISSUE TITLE
github releases

### ISSUE THREAD

**Issue by nett00n** [Kylmakalle/tgvkbot#38]
Было бы здорово, если вы использовали функциональность гитхаба Release - удобно подписываться на анонсы релизов в одном месте через кнопку watch. 
https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

**Comment by Kylmakalle** [comment]
Привет. Всех энтузистов приглашаю подписаться на канал в Telegram.

Софтовая часть, обычно, чуть меньше интересна, поэтому релизы в Github не делаются.
https://t.me/tg_vk
