### ISSUE TITLE
Кодировка

### ISSUE THREAD

**Issue by loskiq** [Kylmakalle/tgvkbot#7]
Проблема с кодировкой

```SyntaxError: Non-ASCII character '\xe2' in file bot.py on line 39, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details```

Как исправить?

**Comment by Kylmakalle** [comment]
Python 2?

**Comment by loskiq** [comment]
@Kylmakalle да

**Comment by Kylmakalle** [comment]
@loskiq
Попробуй в первую строчку bot.py и vk_messages.py добавить ``# -*- coding: utf-8 -*-``
